services:
  go-transcoder:
    container_name: go-transcoder
    build:
      context: ./go-transcoder
      dockerfile: Dockerfile
    volumes:
      - ./media/uploads:/media/uploads
    environment:
        DEBUG: "true"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "root"
        POSTGRES_DB: "database"
        POSTGRES_HOST: "postgres"
        POSTGRES_SSL_MODE: "disable"
        RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
        CONVERSION_EXCHANGE: "conversionExchange"
        CONVERSION_QUEUE: "videoConversion_queue"
        CONVERSION_KEY: "videoConversion"
        CONFIRMATION_EXCHANGE: "confirmationExchange"
        CONFIRMATION_QUEUE: "conversionConfirmation_queue"
        CONFIRMATION_KEY: "videoConfirmation"
    tty: true
    stdin_open: true
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  admin-page:
    container_name: admin-page
    build:
      context: ./py-django
      dockerfile: Dockerfile
    volumes:
      - ./media:/media/
      - ./media/thumbnails:/py-django/media/thumbnails
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASSETS_URL: http://nginx:9000
      CONVERSION_KEY: "videoConversion"
      DATABASE_URL: postgres://admin:root@postgres:5432/database
      DJANGO_SUPERUSER_USERNAME: asolheiro
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/" 

  postgres:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "database"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - ./go-transcoder/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "asolheiro@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "database"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s       
      timeout: 10s        
      retries: 5          
      start_period: 10s   

  nginx:
    container_name: nginx
    image: nginx:1.19.10-alpine
    ports:
      - 9000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/media/

  nextjs-frontend:
    container_name: nextjs-front
    build:
      context: ./next-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next-front:/home/node/app
    environment:
      DJANGO_API_URL: http://admin-page:8000/api
    depends_on:
      admin-page:
        condition: service_healthy
    